# Generated by Django 2.0.2 on 2018-04-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Film', 'verbose_name_plural': 'Filmy'},
        ),
    ]
