# Generated by Django 2.0.2 on 2018-04-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(max_length=255, verbose_name='Link do filmu'),
        ),
    ]
