# Generated by Django 2.0.2 on 2018-03-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_remove_user_following'),
        ('account', '0004_auto_20180306_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
