# Generated by Django 2.0.2 on 2018-03-28 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tytuł')),
                ('body', models.TextField(verbose_name='Treść')),
                ('slug', models.SlugField()),
                ('day', models.DateField(help_text='Dzień wydarzenia', verbose_name='Dzień wydarzenia')),
                ('start_time', models.TimeField(help_text='Godzina rozpoczęcia', verbose_name='Godzina rozpoczęcia')),
                ('end_time', models.TimeField(verbose_name='Zakończenie')),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
            },
        ),
    ]
