# Generated by Django 2.0.2 on 2018-04-23 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Tytuł')),
                ('image', models.ImageField(upload_to='events', verbose_name='Miniatura wydarzenia')),
                ('video_url', models.URLField(blank=True, help_text='Jeśli masz zapowiedź wydarzenia w formie wideo, możesz tutaj wstawić. Jeśli prowadzisz live na facebooku, wstaw do niego link, a osoby zainteresowane będą mogły kliknąć "Otrzymaj powiadomienie" bezpośrednio z Żyj świadomie.', null=True, verbose_name='Link do wideo')),
                ('button', models.CharField(default='Więcej informacji', help_text='Możesz zmienić nazwę przycisku wpisując na przykład: "Bilety"', max_length=100, verbose_name='Przycisk')),
                ('button_url', models.URLField(default='http://przykladowylink.pl', help_text='Przekierowanie przycisku na podany adres, tutaj wpisz adres na który chcesz skierować ludzi zainteresowanych wydarzeniem.', verbose_name='Adres url przycisku')),
                ('body', models.TextField(verbose_name='Treść')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('day', models.DateField(help_text='Dzień wydarzenia', verbose_name='Dzień wydarzenia')),
                ('start_time', models.TimeField(blank=True, help_text='Godzina rozpoczęcia', null=True, verbose_name='Godzina rozpoczęcia')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Godzina zakończenia')),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
            },
        ),
    ]
