# Generated by Django 2.0.2 on 2018-04-23 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-published'], 'verbose_name': 'Wydarzenie', 'verbose_name_plural': 'Wydarzenia'},
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
