# Generated by Django 2.0.2 on 2018-03-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='button',
            field=models.CharField(default='Więcej informacji', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='button_url',
            field=models.URLField(default='przykladowylink.pl'),
        ),
    ]
