# Generated by Django 2.0.2 on 2018-03-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180329_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='button',
            field=models.CharField(default='Więcej informacji', help_text='Możesz zmienić nazwę przycisku wpisując na przykład: "Bilety"', max_length=100, verbose_name='Przycisk'),
        ),
        migrations.AlterField(
            model_name='event',
            name='button_url',
            field=models.URLField(default='przykladowylink.pl', help_text='Przekierowanie przycisku na podany adres, tutaj wpisz adres na który chcesz skierować ludzi zainteresowanych wydarzeniem.', verbose_name='Adres url przycisku'),
        ),
    ]
