# Generated by Django 2.0.2 on 2018-04-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180329_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='button_url',
            field=models.URLField(default='http://przykladowylink.pl', help_text='Przekierowanie przycisku na podany adres, tutaj wpisz adres na który chcesz skierować ludzi zainteresowanych wydarzeniem.', verbose_name='Adres url przycisku'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(verbose_name='Godzina zakończenia'),
        ),
    ]
