# Generated by Django 2.0.2 on 2018-04-20 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('webinar', embed_video.fields.EmbedVideoField()),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='webinars')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default='test', max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webinar',
                'verbose_name_plural': 'Webinary',
            },
        ),
    ]
